remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jemoji
  - jekyll-remote-theme
title: AutoDNS
description: Reach out to your docker containers using their names instead of IP Address
show_downloads: true
