# This is automatically generated by docker-gen

global
  stats socket /var/run/api.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
  daemon
  maxconn         4096
#  log /dev/log    local0
#  log /dev/log    local1 notice

defaults
  log     global
  mode    http
  option  httplog
  option  dontlognull

  timeout connect 5s
  timeout client 50s
  timeout server 50s
  timeout tunnel 1h
  timeout client-fin 50s

  option  http-server-close

frontend stats
  bind *:80
  stats enable
  stats refresh 5s

frontend http-in
  bind *:80
{{range $hostname, $containers := groupByMulti . "Env.HOSTNAME" ","}}
  {{if gt (len $containers) 1}}
    {{$container := (index $containers 0)}}
  acl {{$container.Name}} hdr(host) -i {{$hostname}}
  use_backend {{$hostname}} if {{$container.Name}}
  {{end}}
{{end}}

{{range $hostname, $containers := groupByMulti . "Env.HOSTNAME" ","}}
  {{if gt (len $containers) 1}}
backend {{$hostname}}
  balance leastconn
  option httpclose
  option forwardfor
    {{range $key, $container := $containers}}
  server {{$container.Name}} {{with index $container.Networks 0}}{{.IP}}{{end}}:80 check
    {{end}}
  {{end}}
{{end}}
