# This is automatically generated by docker-gen
{{range $hostname, $containers := groupByMulti . "Env.HOSTNAME" ","}}
{{range $key, $container := $containers}}
{{with index $container.Networks 0}}{{.IP}}{{end}} {{$hostname}}
{{end}}
{{end}}
